spring:
  application:
    name: authentication-gateway
  r2dbc:
    url: r2dbc:mysql://[your-db-host]/authentication
    username: [your-db-username]
    password: [your-db-password]
  cloud: # Using Eureka discovery
    gateway:
      discovery:
        locator:
          enabled: true


logging:
  level:
    org:
      springframework:
        ldap: debug
        r2dbc:
          core: debug
        boot.autoconfigure: error
        cache: trace

eureka:
  client:
    service-url:
      defaultZone: http://[your-eureka-server-host]/eureka/
    enabled: true


management:
  health:
    circuit-breakers:
      enabled: true # /actuator/health
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true


ldap:
  url: ldap://[your-ldap-host]
  base: [your-ldap-base]
  username: [your-ldap-admin-name]
  password: [your-ldap-admin-pwd]


springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
