### 토큰 발급 (서비스 지정 시, 해당 서비스에 해당하는 권한을 가져온다)
POST http://localhost:8080/auth/token
Content-Type: application/json

{
  "username": "msuseol",
  "password": "!gkehdbs1234"
}

### 권한체크1
GET http://localhost:8080/greeting
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiU1lTQURNSU4iLCJhdXRoIjpbXSwiaWQiOiJtc3VzZW9sIiwiZXhwIjoxNzEwNDY2Mzc2fQ.gblRY0jW3oykTXLXDx1Kif9Sqh1IgKtYVr--8qPvyLwqLHCLJR1WIXePnE0CUPhutS0s7EETnwQNoI40B8an2Q

### 권한체크2
GET http://localhost:8080/greeting2?name=msseol
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiU1lTQURNSU4iLCJhdXRoIjpbXSwiaWQiOiJtc3VzZW9sIiwiZXhwIjoxNzEwNDY4NzQyfQ.tLQv6OjS5AhwbEUgM63IYsmUgPJ3al85zy7aWvdrAwvjJYOx-etFcS23edT0SOLLvan0ljKBWpjLywyFKhSbhg

### 권한체크3
GET http://localhost:8080/greeting3?name=msseol
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiU1lTQURNSU4iLCJhdXRoIjpbXSwiaWQiOiJtc3VzZW9sIiwiZXhwIjoxNzEwNDY4NzQyfQ.tLQv6OjS5AhwbEUgM63IYsmUgPJ3al85zy7aWvdrAwvjJYOx-etFcS23edT0SOLLvan0ljKBWpjLywyFKhSbhg
