### 토큰 발급 (서비스 지정 시, 해당 서비스에 해당하는 권한을 가져온다)
POST http://localhost:8080/auth/token
Content-Type: application/json

{
  "username": "msuseol",
  "password": "!gkehdbs1234"
}

### 권한체크1
POST http://localhost:8080/SOCKET-SAMPLE/webhook
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiTk9ORSIsImF1dGgiOlsiZG1fYXNzZXRfciIsImRtX2F1ZGl0bG9nX3IiLCJkbV9idWlsZHN0YXR1c19tb2R1bGVfciIsImRtX2J1aWxkc3RhdHVzX3Byb2R1Y3RfciIsImRtX2J1aWxkc3RhdHVzX3IiLCJkbV9jaGFuZ2VmaWxlc2luZm9fciIsImRtX2Rhc2hib2FyZF9yIiwiZG1fZGV2aWNlX3IiLCJkbV9qZW5raW5zX3IiLCJkbV9tb2R1bGVfciIsImRtX21vZHVsZWJ1aWxkX3IiLCJkbV9ub3RpY2VfciIsImRtX3A0Y2hhbmdlbGlzdHNfciIsImRtX3Byb2R1Y3RfciIsImRtX3Byb2R1Y3RwYWNrYWdlX3IiLCJkbV9zY2hlZHVsZXJfbG9nX3IiLCJkbV9zY2hlZHVsZXJfciIsImRtX3N0cmVhbV9yIiwiZG1fc3Vic2NyaXB0aW9uX3IiLCJkbV90ZXN0X3IiLCJuZXcuc2FtcGxlLmhhaGEiXSwiaWQiOiJtc3VzZW9sIiwiZXhwIjoxNzExMDcwODc4fQ.B50UD1O6tL8EnDMgcbJLNJgFxH9Flpg3hDKfp6xhNnl7_J46JfymPvPVCJhlG73FTfDQMu9ESOefvsAnUM-rXw

{
  "hi": "hello"
}

### 권한체크2
GET http://localhost:8080/greeting2?name=msseol
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiU1lTQURNSU4iLCJhdXRoIjpbXSwiaWQiOiJtc3VzZW9sIiwiZXhwIjoxNzEwNDY4NzQyfQ.tLQv6OjS5AhwbEUgM63IYsmUgPJ3al85zy7aWvdrAwvjJYOx-etFcS23edT0SOLLvan0ljKBWpjLywyFKhSbhg

### 권한체크3
GET http://localhost:8080/greeting3?name=msseol
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiU1lTQURNSU4iLCJhdXRoIjpbXSwiaWQiOiJtc3VzZW9sIiwiZXhwIjoxNzEwNDY4NzQyfQ.tLQv6OjS5AhwbEUgM63IYsmUgPJ3al85zy7aWvdrAwvjJYOx-etFcS23edT0SOLLvan0ljKBWpjLywyFKhSbhg
