# 로컬 레벨 소스코드까지 컨테이너로 복제 후 빌드하고, 이미지를 생성한다
# 일부 방화벽문제, 컨테이너환경 문제로 인하여 사용 불가능한 경우가 종종 있음
FROM mcr.microsoft.com/openjdk/jdk:21-ubuntu as builder
COPY . /usr/src/scaffold
WORKDIR /usr/src/scaffold

RUN ./gradlew build -x test

ENTRYPOINT ["java", "-jar", "./build/libs/spring-scaffold-boot3-0.0.1-SNAPSHOT.jar"]

EXPOSE 8080
