# 업무환경상 gradle-wrapper 다운로드가 불가능할 떄 사용
# gradle까지 설치된 이미지를 사용한다.
FROM gradle:jdk21
COPY . /usr/src/scaffold
WORKDIR /usr/src/scaffold

RUN gradle build -x test

ENTRYPOINT ["java", "-jar", "./build/libs/spring-scaffold-boot3-0.0.1-SNAPSHOT.jar"]

EXPOSE 8080
