### 토큰 발급 (당연히 테스트라서 GET..ㅎㅎㅋ)
GET http://localhost:8080/tokens

### 권한이 없이 가능한 요청
GET http://localhost:8080/greeting

### 권한이 필요한 요청
GET http://localhost:8080/greeting/user
X-Service-Token: eyJhbGciOiJIUzUxMiJ9.eyJpZCI6IlNhbXBsZVVzZXIiLCJhdXRoTGlzdCI6WyJST0xFX1VTRVIiXSwiZXhwIjoxNzA5NzkzNTE4fQ.bOCbqD__WZdL6M-4NH-epv3Ka2TclgdLZhxG3d_EId7_CMftFKU2qJy-3nsezmnXZRmNmX0L6LIfMT5TOmEfeA
